export const ProductType = {
  PENCIL: 1,
  ERASER: 2,
  BALL_PEN: 3,
  GEL_PEN: 4,
  CRAYONS: 5,
  SKETCH_PENS: 6,
  MARKER: 7,
  SCALE: 8,
}

export const brandList = [
  'Apsara', 'DOMS', 'Cello', 'Elkos', 'Nataraj', 'Rorito'
]

export const categoryList = [
  { label: 'All', value: 0 },
  { label: 'Pencil', value: ProductType.PENCIL },
  { label: 'Eraser', value: ProductType.ERASER },
  { label: 'Ball Pen', value: ProductType.BALL_PEN },
  { label: 'Gel Pen', value: ProductType.GEL_PEN },
  { label: 'Crayons', value: ProductType.CRAYONS },
  { label: 'Sketch Pens', value: ProductType.SKETCH_PENS },
  { label: 'Marker', value: ProductType.MARKER },
  { label: 'Scale', value: ProductType.SCALE },
]

export const productImageMapping = [
  {
    name: "Apsara Matt Magic",
    brand: "Apsara",
    type: ProductType.PENCIL,
    description: "Pack of 10 colourful pencils",
    path: "/assets/images/products/apsara_matt_magic.png",
  },
  {
    name: "Apsara Platinum Pencils",
    brand: "Apsara",
    type: ProductType.PENCIL,
    description: "Pack of 10 Pencils with 1 Erasers & 1 Sharpener",
    path: "/assets/images/products/apsara_platinum_pencil.jpg",
  },
  {
    name: "Apsara Non-Dust Erasers",
    brand: "Apsara",
    type: ProductType.ERASER,
    description: "Pack of Non-Dust eraser",
    path: "/assets/images/products/apsara_non_dust_eraser.jpg",
  },
  {
    name: "Apsara Non-Dust Jumbo Erasers",
    brand: "Apsara",
    type: ProductType.ERASER,
    description: "Pack of Non-Dust Jumbo eraser",
    path: "/assets/images/products/apsara_non_dust_jumbo.jpg",
  },
  {
    name: "Cello Butterflow",
    brand: "Cello",
    type: ProductType.BALL_PEN,
    description: "Pack of 20 Blue Ball Pens",
    path: "/assets/images/products/cello_butterflow_blue_ball_pen.jpg",
  },
  {
    name: "Cello Buttergel",
    brand: "Cello",
    type: ProductType.GEL_PEN,
    description: "Pack of 20 Blue Gel Pens",
    path: "/assets/images/products/cello_buttergel_pen_20_pc_pack.jpg",
  },
  {
    name: "Cello Superstar Gel",
    brand: "Cello",
    type: ProductType.GEL_PEN,
    description: "Pack of 20 Blue Gel Pens",
    path: "/assets/images/products/cello_superstar_gell_pen.jpg",
  },
  {
    name: "Elkos Better Ball Pen",
    brand: "Cello",
    type: ProductType.BALL_PEN,
    description: "Pack of 20 Blue Ball Pen",
    path: "/assets/images/products/elkos_better_ball_pen.jpg",
  },
  {
    name: "DOMS Neon",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "Pack of 10 Colourful Pencils with 1 Sharpener",
    path: "/assets/images/products/doms_neon_pencil.jpg",
  },
  {
    name: "DOMS Y1+ Pencils",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "Pack of 10 Pencils with 1 Eraser & 1 Sharpener",
    path: "/assets/images/products/doms_y1_pencil.jpg",
  },
  {
    name: "DOMS Zoom Triangle",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "Pack of 10 with 1 Triangle Eraser & 1 Sharpener",
    path: "/assets/images/products/doms_zoom_triangle_pencil.jpg",
  },
  {
    name: "DOMS 30cm (12 inch) Scale",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "",
    path: "/assets/images/products/doms_30cm_scale.jpg",
  },
  {
    name: "DOMS Scale 15cm (6 inch)",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "",
    path: "/assets/images/products/doms_15cm_scale.jpg",
  },
  {
    name: "DOMS Neon Hex Eraser",
    brand: "DOMS",
    type: ProductType.ERASER,
    description: "",
    path: "/assets/images/products/doms_eraser_neon.jpg",
  },
  {
    name: "DOMS Dust Free Eraser",
    brand: "DOMS",
    type: ProductType.ERASER,
    description: "",
    path: "/assets/images/products/doms_extra_long_eraser.png",
  },
  {
    name: "DOMS Coloured Erasers",
    brand: "DOMS",
    type: ProductType.ERASER,
    description: "20 Pcs",
    path: "/assets/images/products/doms_long_colored_eraser.png",
  },
  {
    name: "DOMS Triangle Eraser",
    brand: "DOMS",
    type: ProductType.ERASER,
    description: "20 Pcs",
    path: "/assets/images/products/doms_triangle_erasers.jpg",
  },
  {
    name: "DOMS Wax Crayons",
    brand: "DOMS",
    type: ProductType.CRAYONS,
    description: "12 Shades",
    path: "/assets/images/products/doms_wax_crayons.png",
  },
  {
    name: "DOMS Mini Sketch Pens",
    brand: "DOMS",
    type: ProductType.SKETCH_PENS,
    description: "12 Shades",
    path: "/assets/images/products/doms_mini_sketch_pens.jpg",
  },
  {
    name: "DOMS Sketch Pens",
    brand: "DOMS",
    type: ProductType.SKETCH_PENS,
    description: "12 Shades",
    path: "/assets/images/products/doms_sketch_pens.jpg",
  },
  {
    name: "DOMS Colour Pencils",
    brand: "DOMS",
    type: ProductType.PENCIL,
    description: "12 Shades",
    path: "/assets/images/products/doms_colour_pencil_12_shades.png",
  },
  {
    name: "6 DOMS Tempera Colours",
    brand: "DOMS",
    type: ProductType.SKETCH_PENS,
    description: "",
    path: "/assets/images/products/doms_tempera_colors_6.jpg",
  },
  {
    name: "DOMS Tempra Colours",
    brand: "DOMS",
    type: ProductType.SKETCH_PENS,
    description: "",
    path: "/assets/images/products/doms_tempra_color_pen.png",
  },
  {
    name: "Rorito Josh Gel",
    brand: "Rorito",
    type: ProductType.GEL_PEN,
    description: "Blue Gel Pens",
    path: "/assets/images/products/rorito_josh.jpg",
  },
  {
    name: "Rorito Fanta Flo",
    brand: "Rorito",
    type: ProductType.BALL_PEN,
    description: "Blue Ball Pens",
    path: "/assets/images/products/rorita_fanta_flo_ball_pen.jpg",
  },
  {
    name: "Rorito HD Marker",
    brand: "Rorito",
    type: ProductType.MARKER,
    description: "Permanent Refillable Marker",
    path: "/assets/images/products/rorita_hd_permanent_marker.png",
  },
  {
    name: "NATARAJ 621 Pencils",
    brand: "NATARAJ",
    type: ProductType.PENCIL,
    description: "",
    path: "/assets/images/products/nataraj_621_bold_pencil.png",
  },
  {
    name: "NATARAJ 621 Scale (15cm)",
    brand: "NATARAJ",
    type: ProductType.SCALE,
    description: "",
    path: "/assets/images/products/nataraj_621_scale.jpg",
  },
  {
    name: "NATARAJ 621 Scale (30cm)",
    brand: "NATARAJ",
    type: ProductType.SCALE,
    description: "",
    path: "/assets/images/products/nataraj_621_30cm_scale.jpg",
  },
  {
    name: "Elkos Better",
    brand: "Elkos",
    type: ProductType.BALL_PEN,
    description: "Blue Ball Pens",
    path: "/assets/images/products/elkos_better_ball_pen.jpg",
  },
  {
    name: "Elkos Oxer",
    brand: "Elkos",
    type: ProductType.BALL_PEN,
    description: "Blue Ball Pens",
    path: "/assets/images/products/elkos_oxer_ball_pen.jpg",
  },
  {
    name: "Elkos Shine",
    brand: "Elkos",
    type: ProductType.BALL_PEN,
    description: "Blue Ball Pens",
    path: "/assets/images/products/elkos_shine_ball_pen.jpg",
  },
];
